/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVouchersRouteImport } from './routes/_app/vouchers'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppRevenueRouteImport } from './routes/_app/revenue'
import { Route as AppPortalRouteImport } from './routes/_app/portal'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppNodesRouteImport } from './routes/_app/nodes'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBackhaulsRouteImport } from './routes/_app/backhauls'
import { Route as AppAdsRouteImport } from './routes/_app/ads'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVouchersRoute = AppVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesRoute = AppNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBackhaulsRoute = AppBackhaulsRouteImport.update({
  id: '/backhauls',
  path: '/backhauls',
  getParentRoute: () => AppRoute,
} as any)
const AppAdsRoute = AppAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ads': typeof AppAdsRoute
  '/backhauls': typeof AppBackhaulsRoute
  '/dashboard': typeof AppDashboardRoute
  '/nodes': typeof AppNodesRoute
  '/notifications': typeof AppNotificationsRoute
  '/portal': typeof AppPortalRoute
  '/revenue': typeof AppRevenueRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/vouchers': typeof AppVouchersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ads': typeof AppAdsRoute
  '/backhauls': typeof AppBackhaulsRoute
  '/dashboard': typeof AppDashboardRoute
  '/nodes': typeof AppNodesRoute
  '/notifications': typeof AppNotificationsRoute
  '/portal': typeof AppPortalRoute
  '/revenue': typeof AppRevenueRoute
  '/sessions': typeof AppSessionsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/vouchers': typeof AppVouchersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ads': typeof AppAdsRoute
  '/_app/backhauls': typeof AppBackhaulsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/nodes': typeof AppNodesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/revenue': typeof AppRevenueRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/vouchers': typeof AppVouchersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ads'
    | '/backhauls'
    | '/dashboard'
    | '/nodes'
    | '/notifications'
    | '/portal'
    | '/revenue'
    | '/sessions'
    | '/settings'
    | '/users'
    | '/vouchers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ads'
    | '/backhauls'
    | '/dashboard'
    | '/nodes'
    | '/notifications'
    | '/portal'
    | '/revenue'
    | '/sessions'
    | '/settings'
    | '/users'
    | '/vouchers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ads'
    | '/_app/backhauls'
    | '/_app/dashboard'
    | '/_app/nodes'
    | '/_app/notifications'
    | '/_app/portal'
    | '/_app/revenue'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/vouchers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vouchers': {
      id: '/_app/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AppVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revenue': {
      id: '/_app/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes': {
      id: '/_app/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AppNodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backhauls': {
      id: '/_app/backhauls'
      path: '/backhauls'
      fullPath: '/backhauls'
      preLoaderRoute: typeof AppBackhaulsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ads': {
      id: '/_app/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AppAdsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdsRoute: typeof AppAdsRoute
  AppBackhaulsRoute: typeof AppBackhaulsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNodesRoute: typeof AppNodesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPortalRoute: typeof AppPortalRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVouchersRoute: typeof AppVouchersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdsRoute: AppAdsRoute,
  AppBackhaulsRoute: AppBackhaulsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNodesRoute: AppNodesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPortalRoute: AppPortalRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppVouchersRoute: AppVouchersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
